@APISIX_ADMIN_KEY=edd1c9f034335f136f87ad84b625c8f1
@CLIENT_API_KEY=abcdefghijk2026xyz
@CLIENT_API_KEY_2=abcdefghijk2026xyzmno
@RESOURCE_NAME=groffefoundry02
@DEPLOYMENT_NAME=gpt-5.5
@AZURE_AI_API_VERSION=2024-10-21
@ROUTE_APISIX=/azure-ai/maf


###
# PASSO 1: Configurar traces do APISIX para OpenTelemetry
curl http://127.0.0.1:9180/apisix/admin/plugin_metadata/opentelemetry -H "X-API-KEY: {{APISIX_ADMIN_KEY}}" -X PUT -d '
{
    "trace_id_source": "x-request-id",
    "resource": {
      "service.name": "APISIX",
      "deployment.environment.name": "development"
    },
    "collector": {
      "address": "alloy:4318",
      "request_timeout": 3,
      "request_headers": {
      }
    },
    "batch_span_processor": {
      "drop_on_queue_full": false,
      "max_queue_size": 1024,
      "batch_timeout": 2,
      "inactive_timeout": 1,
      "max_export_batch_size": 16
    },
    "set_ngx_var": false
}'


###
# PASSO 2: Criar o Consumer com a API Key do cliente.
curl "http://127.0.0.1:9180/apisix/admin/consumers" -X PUT \
  -H "X-API-KEY: {{APISIX_ADMIN_KEY}}" \
  -d '{
    "username": "consoleappchatai",
    "plugins": {
      "key-auth": {
        "key": "{{CLIENT_API_KEY}}"
      }
    }
  }'


###
# PASSO 3: Criar segundo Consumer com a API Key do cliente.
curl "http://127.0.0.1:9180/apisix/admin/consumers" -X PUT \
  -H "X-API-KEY: {{APISIX_ADMIN_KEY}}" \
  -d '{
    "username": "consoleappchatai2",
    "plugins": {
      "key-auth": {
        "key": "{{CLIENT_API_KEY_2}}"
      }
    }
  }'


###
# PASSO 4: Criar a rota exigindo a API Key do cliente e com um secret 
# para a chave do Microsoft Foundry.
curl "http://127.0.0.1:9180/apisix/admin/routes" -X PUT \
  -H "X-API-KEY: {{APISIX_ADMIN_KEY}}" \
  -d '{
    "id": "azure-ai-gpt-5.5-maf",
    "uri": "{{ROUTE_APISIX}}/*",
    "methods": ["POST"],
    "plugins": {
      "key-auth": {},
      "consumer-restriction": {
          "whitelist": [
              "consoleappchatai"
          ]
      },
      "ai-prompt-guard": {
        "deny_patterns": ["(?i)AWS", "(?i)Amazon", "(?i)Oracle"]
      },
      "opentelemetry": {
        "sampler": {
          "name": "always_on"
        }
      },
      "ai-proxy": {
        "provider": "azure-openai",
        "auth": {
          "header": {
            "api-key": "$env://MICROSOFT_FOUNDRY_API_KEY"
          }
        },
        "options":{
          "model": "{{DEPLOYMENT_NAME}}"
        },
        "timeout": 120000,
        "override": {
          "endpoint": "https://{{RESOURCE_NAME}}.openai.azure.com/openai/deployments/{{DEPLOYMENT_NAME}}/chat/completions?api-version={{AZURE_AI_API_VERSION}}"
        }
      }
    },
    "upstream": {
      "type": "roundrobin",
      "nodes": {
        "httpbin.org": 1
      }
    }
  }'


###
# PASSO 5: Testar a rota criada.
curl http://localhost:9080{{ROUTE_APISIX}}/bla/bla-bla/xpto/worldcup \
  -X POST \
  -H "apikey: {{CLIENT_API_KEY}}" \
  -H "Content-Type: application/json" \
  -d '{
    "messages": [
      { "role": "user", "content": "Fale resumidamente sobre a linguagem C#" }
    ]
  }'


###
# PASSO 6: Testar a rota criada com um consumer inválido.
curl http://localhost:9080{{ROUTE_APISIX}}/bla/bla-bla/xpto/worldcup \
  -X POST \
  -H "apikey: {{CLIENT_API_KEY_2}}" \
  -H "Content-Type: application/json" \
  -d '{
    "messages": [
      { "role": "user", "content": "Fale resumidamente sobre a linguagem C#" }
    ]
  }'


###
# PASSO 7: Testar a rota criada com um termo inválido na pergunta.
curl http://localhost:9080{{ROUTE_APISIX}}/bla/bla-bla/xpto/worldcup \
  -X POST \
  -H "apikey: {{CLIENT_API_KEY}}" \
  -H "Content-Type: application/json" \
  -d '{
    "messages": [
      { "role": "user", "content": "Fale resumidamente sobre Aws" }
    ]
  }'


###
# PASSO 8: Testar novamente a rota criada.
curl http://localhost:9080{{ROUTE_APISIX}}/bla/bla-bla/xpto/worldcup \
  -X POST \
  -H "apikey: {{CLIENT_API_KEY}}" \
  -H "Content-Type: application/json" \
  -d '{
    "messages": [
      { "role": "user", "content": "Fale resumidamente sobre o Microsoft Azure" }
    ]
  }'


###
# PASSO 9: Testar a rota criada com um novo termo inválido na pergunta.
curl http://localhost:9080{{ROUTE_APISIX}}/bla/bla-bla/xpto/worldcup \
  -X POST \
  -H "apikey: {{CLIENT_API_KEY}}" \
  -H "Content-Type: application/json" \
  -d '{
    "messages": [
      { "role": "user", "content": "Fale resumidamente sobre Certificações Oracle" }
    ]
  }'